language: java
sudo: true
jdk:
  - openjdk8

branches:
  only:
    - master
    - develop
    - feature

before_install:
  - chmod +x ./gradlew

cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.gradle'